### PR TITLE
feat: bind socket to a particular device

### PR DESCRIPTION
**Pull request by hellodword**
Usage:

```json
{
    "listen": ":8443",
    "socket_config": {
    	"bind_to_device": "wg0",
	"bind_address": "10.0.0.2"
    }
}
```

Only tested on linux.

### CODE REVIEW

**Comment by tobyxdd** [comment]
This looks good to me. Just that it might be better if we change the name of the option to be more unambiguous - something like `bind_outbound`? (since we already have `socks5_outbound`)

**Comment by tobyxdd** [comment]
I've done the rename, along with some other tweaks.

How do you feel about it? I'm ready to merge when you are.

**Comment by hellodword** [comment]
Great, glad to be merged.

**Comment by enihcam** [comment]
```
Jun 11 16:02:59 hysteria[9612]: 2022-06-11T16:02:59+08:00 [FATA] [error:route ip+net: netlinkrib: address family not supported by protocol] Failed to find the interface
Jun 11 16:02:59 hysteria[9624]: 2022-06-11T16:02:59+08:00 [FATA] [error:route ip+net: netlinkrib: address family not supported by protocol] Failed to find the interface
Jun 11 16:02:59 hysteria[9634]: 2022-06-11T16:02:59+08:00 [FATA] [error:route ip+net: netlinkrib: address family not supported by protocol] Failed to find the interface
Jun 11 16:02:59 hysteria[9643]: 2022-06-11T16:02:59+08:00 [FATA] [error:route ip+net: netlinkrib: address family not supported by protocol] Failed to find the interface
Jun 11 16:03:00 hysteria[9652]: 2022-06-11T16:03:00+08:00 [FATA] [error:route ip+net: netlinkrib: address family not supported by protocol] Failed to find the interface
```

```
$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.1/24 brd 192.168.0.255 scope global eth0
       valid_lft forever preferred_lft forever
```

```json
{
    "listen": ":8443",
    "socket_config": {
    	"bind_to_device": "eth0",
	"bind_address": "192.168.0.1"
    }
}
```

**Comment by hellodword** [comment]
> ```
> Jun 11 16:02:59 hysteria[9612]: 2022-06-11T16:02:59+08:00 [FATA] [error:route ip+net: netlinkrib: address family not supported by protocol] Failed to find the interface
> Jun 11 16:02:59 hysteria[9624]: 2022-06-11T16:02:59+08:00 [FATA] [error:route ip+net: netlinkrib: address family not supported by protocol] Failed to find the interface
> Jun 11 16:02:59 hysteria[9634]: 2022-06-11T16:02:59+08:00 [FATA] [error:route ip+net: netlinkrib: address family not supported by protocol] Failed to find the interface
> Jun 11 16:02:59 hysteria[9643]: 2022-06-11T16:02:59+08:00 [FATA] [error:route ip+net: netlinkrib: address family not supported by protocol] Failed to find the interface
> Jun 11 16:03:00 hysteria[9652]: 2022-06-11T16:03:00+08:00 [FATA] [error:route ip+net: netlinkrib: address family not supported by protocol] Failed to find the interface
> ```
> 
> 
>     
>  
>   
> 
> ```
> $ ip addr
> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
>     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
>     inet 127.0.0.1/8 scope host lo
>        valid_lft forever preferred_lft forever
> 2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
>     link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
>     inet 192.168.0.1/24 brd 192.168.0.255 scope global eth0
>        valid_lft forever preferred_lft forever
> ```
> 
> 
>      
>   
> 
> ```json
> {
>     "listen": ":8443",
>     "bind_outbound": {
> 	"address": "192.168.0.1",
>     	"device": "eth0"
>     }
> }
> ```

try setcap or sudo

https://www.google.com/search?q=so_bindtodevice+capability

**Pull request merged**
