### PR TITLE
Switch tun2socks implementation to xjasonlyu/tun2socks for TUN mode

### LINKED ISSUE #161: freebsd compile error
```hysteria > go build -o hysteria -ldflags "-w -s" ./cmd```
```# github.com/eycorsican/go-tun2socks/core
ld: error: undefined symbol: sys_now
>>> referenced by timeouts.c:299 (/root/.go/pkg/mod/github.com/eycorsican/go-tun2socks@v1.16.11/core/c/core/timeouts.c:299)
>>>               $WORK/b250/_x003.o:(lwip_init)
>>> referenced by timeouts.c:299 (/root/.go/pkg/mod/github.com/eycorsican/go-tun2socks@v1.16.11/core/c/core/timeouts.c:299)
>>>               $WORK/b250/_x003.o:(lwip_init)
>>> referenced by timeouts.c:299 (/root/.go/pkg/mod/github.com/eycorsican/go-tun2socks@v1.16.11/core/c/core/timeouts.c:299)
>>>               $WORK/b250/_x003.o:(lwip_init)
>>> referenced 15 more times
clang: error: linker command failed with exit code 1 (use -v to see invocation)
# github.com/eycorsican/go-tun2socks/core
In file included from /root/.go/pkg/mod/github.com/eycorsican/go-tun2socks@v1.16.11/core/c_core_6.go:8:
/root/.go/pkg/mod/github.com/eycorsican/go-tun2socks@v1.16.11/core/c/core/ipv6/ip6.c:1471:21: warning: format specifies type 'unsigned short' but the argument has type 'unsigned int' [-Wformat]
/root/.go/pkg/mod/github.com/eycorsican/go-tun2socks@v1.16.11/core/c/include/lwip/prot/ip6.h:97:22: note: expanded from macro 'IP6H_V'
/root/.go/pkg/mod/github.com/eycorsican/go-tun2socks@v1.16.11/core/c/include/lwip/debug.h:150:53: note: expanded from macro 'LWIP_DEBUGF'
/root/.go/pkg/mod/github.com/eycorsican/go-tun2socks@v1.16.11/core/c/custom/arch/cc_others.h:83:42: note: expanded from macro 'LWIP_PLATFORM_DIAG'
In file included from /root/.go/pkg/mod/github.com/eycorsican/go-tun2socks@v1.16.11/core/c_core_6.go:8:
/root/.go/pkg/mod/github.com/eycorsican/go-tun2socks@v1.16.11/core/c/core/ipv6/ip6.c:1472:21: warning: format specifies type 'unsigned short' but the argument has type 'unsigned int' [-Wformat]
/root/.go/pkg/mod/github.com/eycorsican/go-tun2socks@v1.16.11/core/c/include/lwip/prot/ip6.h:98:22: note: expanded from macro 'IP6H_TC'
/root/.go/pkg/mod/github.com/eycorsican/go-tun2socks@v1.16.11/core/c/include/lwip/debug.h:150:53: note: expanded from macro 'LWIP_DEBUGF'
/root/.go/pkg/mod/github.com/eycorsican/go-tun2socks@v1.16.11/core/c/custom/arch/cc_others.h:83:42: note: expanded from macro 'LWIP_PLATFORM_DIAG'

### PR DESCRIPTION
**Pull request by haruue**
[xjasonlyu/tun2socks](https://github.com/xjasonlyu/tun2socks) is a better tun2socks implementation than eycorsican/go-tun2socks, this Pull Request switches to xjasonlyu/tun2socks for TUN mode, as our users have requested this change countless times.

Fixes #161, #185, #192, #306, #347, #394, and other issues related to TUN mode or Glibc compatibility.

## Noticeable changes
+ The options `address`, `gateway`, `mask`, `dns`, `persist` in the `tun` config have been removed, and related documents in the wiki should be updated.
+ License has been updated. Executables with TUN mode available need to be built with `-tags=gpl` and distributed under GPLv3. Downstream packaging scripts might need to be updated for this change. The hysteria itself (as a go module or executable without TUN mode) is still available under MIT.
+ GitHub Actions has been updated, `notun` building is removed, and release binaries have been renamed as the following screenshot. Downstream packaging scripts might need to be updated if they download & package binaries from GitHub release.
  image

### CODE REVIEW

**Comment by Error996** [comment]
Finally, i don't have to use tun2socks to create an interface........
Good Job~!

**Comment by Error996** [comment]
Finally, i don't have to use tun2socks to create an interface........
Good Job~!

**Comment by Error996** [comment]
Now there is an obvious problem, if there are more than one server, then there need to have more than one client locally, at this time ，if client use tun mode, then there will be more than one tun interface, and memory consumption is high, wasting computing resources, it is recommended to consider load balancing

**Comment by tobyxdd** [comment]
> Now there is an obvious problem, if there are more than one server, then there need to have more than one client locally, at this time ，if client use tun mode, then there will be more than one tun interface, and memory consumption is high, wasting computing resources, it is recommended to consider load balancing

We have no plans to support multi-servers.

**Comment by Error996** [comment]
Got it

**Review by tobyxdd — APPROVED** [review]

**Pull request merged**
